# -- coding: utf-8 --
"""Twitter Sentiment Analysis AI ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vRXG1auGkQ8jusEW5vVJJU307_X0wqGI
"""

#installing kaggle library
! pip install kaggle

# configuring the path of kaggle.json file
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

"""imoporting twitter sentiment datset"""

#API to fetch the data set from kaggle
!kaggle datasets download -d kazanova/sentiment140

"""Double-click (or enter) to edit"""

from zipfile import ZipFile
dataset = '/content/sentiment140.zip'

with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('dataset is extracted')

"""importing the dependiencies"""

import pandas as pd
import numpy as np
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import nltk
nltk.download('stopwords')

# printing stopwords in english
print(stopwords.words('english'))

"""data processing"""

#loading the dataset from csv file to pandas dataframe

twitter_data = pd.read_csv('/content/training.1600000.processed.noemoticon.csv',encoding='ISO-8859-1')

column_names = ['target' , 'id' , 'date' , 'falg' , 'user' , 'text' ]
twitter_data = pd.read_csv('/content/training.1600000.processed.noemoticon.csv',names = column_names, encoding='ISO-8859-1')

#checking the number of rows and columns
twitter_data.shape

#printing the first 5 rows of data frame
twitter_data.head()

#naming the columns and reading the dataset again
column_names = ['target' , 'id' , 'date' , 'falg' , 'user' , 'text' ]
twitter_data = pd.read_csv('/content/training.1600000.processed.noemoticon.csv',names = column_names, encoding='ISO-8859-1')

twitter_data.head()

#counting the number of missing data
twitter_data.isnull().sum()

#checking the distribution of target column
twitter_data['target'].value_counts()

"""converting the target from 4 to 1"""

twitter_data.replace({'target' : {4:1}}, inplace = True)

twitter_data['target'].value_counts()

"""o--> negative tweet and 1--> positive tweet

stemming= reducing a word to its root word
"""

#stemming
port_stem = PorterStemmer()

def stemming(content):
  stemmed_content = re.sub('[^a-zA-Z]',' ',content)
  stemmed_content = stemmed_content.lower()
  stemmed_content = stemmed_content.split()
  stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content = ' '.join(stemmed_content)
  return stemmed_content

twitter_data['stemmed content'] = twitter_data['text'].apply(stemming) #takes about 25 minutes !!!!

twitter_data.head()

print (twitter_data['stemmed content'])

print (twitter_data['target'])

#seperating the data and label.
x= twitter_data['stemmed content'].values
y= twitter_data['target'].values

print(x)

print(y)

#spliting the dataset into training and testing data.

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)

print (x.shape, x_train.shape, x_test.shape)

print(x_train)

print(x_test)

#converting textual data into numerical data

vectorizer = TfidfVectorizer()

x_train = vectorizer.fit_transform(x_train)
x_test = vectorizer.transform(x_test)

print(x_train)

print(x_test)

"""Training the ML model"""

model = LogisticRegression(max_iter=1000)

model.fit(x_train, y_train)

"""Model Evaluation

Accuracy score
"""

# Accuracy score on the traning data

x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(y_train, x_train_prediction)

print('accuracy score on training data :', training_data_accuracy)

# Accuracy score on the test data

x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(y_test, x_test_prediction)

print('accuracy score on test data :', test_data_accuracy)

"""Model Acuraccy is 77.66 %

Saving the trained model
"""

import pickle

filename= 'trained_model.sav'
pickle.dump(model,open(filename,'wb'))

"""Using the saved model for future prediction"""

#loding the saved model

loaded_model = pickle.load(open('trained_model.sav','rb'))

print(twitter_data.iloc[200]['text']) # prints the original csv

x_new = x_test[200]
print(y_test[200])

prediction= loaded_model.predict(x_new)
print(prediction)

if (prediction[0]==0):
  print('negative tweet')
else:
  print('positive tweet')

x_new = x_test[3]
print(y_test[3])

prediction= loaded_model.predict(x_new)
print(prediction)

if (prediction[0]==0):
  print('negative tweet')
else:
  print('positive tweet')

x_new = x_test[19]
print(y_test[19])

prediction= loaded_model.predict(x_new)
print(prediction)

if (prediction[0]==0):
  print('negative tweet')
else:
  print('positive tweet')
